import "./globals.css";
import { Inter } from "next/font/google";
import Aside from "../components/Aside";
import Header from '../components/Header'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Alaa Ayaad</title>
      </head>
      <body>
        <Aside />
        <div className="main">
          <Header />
          <div className="res__div">{children}</div>
        </div>
      </body>
    </html>
  );
}
