"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Aside from "../components/Aside";
import Header from "../components/Header";
import Spinner from "../components/spinner/Spinner";
import { useEffect, useState } from "react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 1500);
  }, []);
  return (
    <html lang="en">
      <head>
        <title>Alaa Ayaad</title>
      </head>

      {loading ? (
        <Spinner />
      ) : (
        <body>
          <Aside />
          <div className="main">
            <Header />
            <div className="res__div">{children}</div>
          </div>
        </body>
      )}
    </html>
  );
}
